### PR TITLE
Created a nice new layout for the site

### PR DESCRIPTION
**Pull request by nickavv**
I abandoned the Github Pages "theme" stuff.. hopefully this will render correctly when merged to master!

image

### CODE REVIEW

**Comment by nickavv** [comment]
I left the bottom area of the content blank but it should be easy enough to fill in with projects, links, information, etc. And the page at least looks better than what we have now

**Comment by nickavv** [comment]
Just updated PR with some CSS to do some responsive design, so at the size of the screenshot I posted above the "Charting the course for open source" will be all on one line.

And down to mobile-like sizes it will drop the gutters on the sides:
image

**Comment by romeara** [comment]
@nickavv Looks awesome, but that top line seems unfinished? "to make...."?

**Comment by nickavv** [comment]
Wow... you're right  :) I must have gotten distracted mid-thought. Let me finish that haha

**Review by romeara — APPROVED** [review]
Looks awesome!

**Pull request merged**
